version: '3.8'

services:
  kifiya-cafe:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 45s
      timeout: 30s
      retries: 5
      start_period: 30s

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=kifya_cafe_yt
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Bikila@123
      - MYSQL_ROOT_PASSWORD=Bikila@123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 10s

volumes:
  mysql_data:
    driver: local